language: node_js
node_js:
- '8'
- '10'
cache: yarn
script: yarn ci
deploy:
  provider: npm
  email: igor@kamyshev.me
  skip_cleanup: true
  api_key:
    secure: QH3ms93DY2R2TsePykhUEVRgUcvaOe+UW3Eu43sDh2xghoKeISS5uXCNFQCpEBh0V61moFNRcfqstFYf1oaT6LciLvn8+Ej+owf6QAbDi2vqs+oKXykUUg5znYiqDVSK2d/npSF8oIrmzJZeRCIbgALsgh0WY2Sf/HVYWPZtH4y6RsJJFXdlAw+CDnoT/DZLaf1/6uX6O5T+gQcAIa8VSPoPlz/mwKfAuh4JgUmkCVO09QAE58Uop8m5vi9OBqgoN71kdN561ZpUpEw5JbeO2dcEJCj/9KFzT/jnrqY44WvRAc1zacX+XnBTFYxaqSygP1CwJ7GwIZOymlxps4P/ke78en19DKoMGb6+bJ3lQzKAtoXqhKo2+y8EqhUC0InoLZHLSnoVPuCEb5OEU7esBJLaq4LKgbgknDvwjLqUwA/huRXCzzqfm9zaPq5AsbhDNouNVJotbRLhkDCaz6P62PV4ScdJUpxZvBMxrS43t7M6YELzfEbA3u8X6DzdQSKcURWpj9JdcsfevQOdHOoQA9JA2+MCAQdGS7IvoMxerQ8oqDCVPj07z5N9nkrT0lQtKc7HGdXUVzo9r+iONdz1Jylpd8yjHzlW28BO/KxRrGnjk6JeBVtxYAUOb5NAnGv/Vrf+6NCf54PBgHUYUNlAcLasydT18+Utuc1CXhHZ08E=
  on:
    tags: true
    repo: solid-soda/cache
